%
% $Id: vasProlog.cpp,v 1.7.8.4 2011-09-29 09:18:04 kkr Exp $
%
% File generated by HeKatE Qt Editor ver. M6_10_1
%
% HeaRT case
%
%
%     Copyright (C) 2006-9 by the HeKatE Project
%
%     HeaRT has been develped by the HeKatE Project, 
%     see http://hekate.ia.agh.edu.pl
%
%     This file is part of HeaRT.
%
%     HeaRT is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     HeaRT is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with HeaRT.  If not, see <http://www.gnu.org/licenses/>.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

:- ensure_loaded('heart.pl').

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TYPES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%

xtype [name: boolean,
       base: numeric,
       desc: boolean,
       domain: [0,1]
      ].
xtype [name: numeric,
       base: numeric,
       desc: integer,
       domain: [-2147483647 to 2147483647]
      ].


xtype [name: ard_default_type,
       base: symbolic,
       domain: [none/1],
       ordered: yes
      ].
xtype [name: typeCarAccidents,
       base: numeric,
       desc: 'The number of accidents in the last yaer',
       domain: [0 to 366]
      ].
xtype [name: typeDriverAge,
       base: numeric,
       desc: 'The age of car, driver, etc',
       domain: [18 to 120]
      ].
xtype [name: typeCarCapacity,
       base: numeric,
       desc: 'The car capacity in ccm',
       domain: [0 to 10000]
      ].
xtype [name: typeDiscount,
       base: numeric,
       desc: 'The sum of discounts in percents',
       domain: [-100 to 10000]
      ].
xtype [name: typeDriverClass,
       base: numeric,
       desc: 'The class of a client',
       domain: [-1 to 9]
      ].
xtype [name: typeInsurancePayment,
       base: symbolic,
       domain: [single/1,instalments/2],
       ordered: yes
      ].
xtype [name: typeInsuranceCars,
       base: numeric,
       domain: [0 to 1000]
      ].
xtype [name: typeCarSeats,
       base: numeric,
       domain: [1 to 10]
      ].
xtype [name: typeCarAge,
       base: numeric,
       domain: [0 to 200]
      ].
xtype [name: typeDriverLicage,
       base: numeric,
       domain: [0 to 102]
      ].

%%%%%%%%%%%%%%%%%%%%%%%%% ATTRIBUTES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%

xattr [name: carDiscount,
       abbrev: carD1,
       class: simple,
       type: ard_default_type,
       comm: inter,
       desc: 'The sum of the car discounts'
      ].
xattr [name: driverDiscount,
       abbrev: driv2,
       class: simple,
       type: ard_default_type,
       comm: inter,
       desc: 'The sum of driver discounts'
      ].
xattr [name: baseModifierValue,
       abbrev: base1,
       class: simple,
       type: numeric,
       comm: inter,
       desc: 'The sum of others discounts'
      ].
xattr [name: baseValue,
       abbrev: base2,
       class: simple,
       type: numeric,
       comm: inter,
       desc: 'The base insurance charge'
      ].
xattr [name: carAccidents,
       abbrev: carA2,
       class: simple,
       type: typeCarAccidents,
       comm: in,
       desc: 'The number of accidents in the last year'
      ].
xattr [name: carAge,
       abbrev: carA1,
       class: simple,
       type: typeCarAge,
       comm: in,
       desc: 'The car age'
      ].
xattr [name: carCapacity,
       abbrev: carC1,
       class: simple,
       type: typeCarCapacity,
       comm: in,
       desc: 'Car capacity'
      ].
xattr [name: carHistoric,
       abbrev: carH1,
       class: simple,
       type: boolean,
       comm: in,
       desc: 'Indicates if the car is a antique car'
      ].
xattr [name: carSeats,
       abbrev: carS1,
       class: simple,
       type: typeCarSeats,
       comm: in,
       desc: 'The number of seats in the car'
      ].
xattr [name: carTechnical,
       abbrev: carT1,
       class: simple,
       type: boolean,
       comm: in,
       desc: 'Indicates if a car passed test of technical state'
      ].
xattr [name: driverAge,
       abbrev: driv1,
       class: simple,
       type: typeDriverAge,
       comm: in,
       desc: 'The age of a driver'
      ].
xattr [name: driverClass,
       abbrev: driv4,
       class: simple,
       type: typeDriverClass,
       comm: inter,
       desc: 'The class of a client'
      ].
xattr [name: driverLicage,
       abbrev: driv5,
       class: simple,
       type: typeDriverLicage,
       comm: in,
       desc: 'The driver age'
      ].
xattr [name: insuranceCars,
       abbrev: insu5,
       class: simple,
       type: typeInsuranceCars,
       comm: in,
       desc: 'The number of car insurnace'
      ].
xattr [name: insuranceCertificate,
       abbrev: insu3,
       class: simple,
       type: boolean,
       comm: in,
       desc: 'Indicates if a client has a insurance history'
      ].
xattr [name: insuranceContinue,
       abbrev: insu1,
       class: simple,
       type: boolean,
       comm: in,
       desc: 'Indicates if it is a insurance continuation'
      ].
xattr [name: insuranceOtherins,
       abbrev: insu2,
       class: simple,
       type: boolean,
       comm: in,
       desc: 'Indicates if a client has an other insurance'
      ].
xattr [name: insurancePayment,
       abbrev: insu4,
       class: simple,
       type: typeInsurancePayment,
       comm: in,
       desc: 'The number of installments'
      ].
xattr [name: resultValue,
       abbrev: resu1,
       class: simple,
       type: numeric,
       comm: out,
       desc: 'The final insurance price'
      ].

%%%%%%%%%%%%%%%%%%%%%%%% TABLE SCHEMAS DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%

xschm main: [baseModifierValue,baseValue] ==> [resultValue].
xschm bonusMalus: [carAccidents,driverClass] ==> [driverClass].
xschm baseCharge: [carCapacity] ==> [baseValue,resultValue].
xschm baseChargeModifiers: [driverClass,driverAge,carAge,insurancePayment,insuranceContinue,insuranceCars,insuranceOtherins,carHistoric,driverLicage,carSeats,carTechnical,insuranceCertificate] ==> [baseModifierValue].

%%%%%%%%%%%%%%%%%%%%%%%%%%%% RULES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%

xrule main/1:
      [baseModifierValue eq any,
       baseValue eq any]
    ==>
      [resultValue set (baseValue+(baseValue*(baseModifierValue/100.000)))].

xrule bonusMalus/1:
      [carAccidents eq 0,
       driverClass in [-1 to 8]]
    ==>
      [driverClass set (driverClass+1)]
    :baseCharge.
xrule bonusMalus/2:
      [carAccidents eq 0,
       driverClass eq 9]
    ==>
      [driverClass set 9]
    :baseCharge.
xrule bonusMalus/3:
      [carAccidents gt 0,
       driverClass in [-1,0]]
    ==>
      [driverClass set -1]
    :baseCharge.
xrule bonusMalus/4:
      [carAccidents eq 1,
       driverClass eq 1]
    ==>
      [driverClass set 0]
    :baseCharge.
xrule bonusMalus/5:
      [carAccidents eq 1,
       driverClass in [2 to 5,8,9]]
    ==>
      [driverClass set (driverClass-2)]
    :baseCharge.
xrule bonusMalus/6:
      [carAccidents eq 1,
       driverClass in [6 to 7]]
    ==>
      [driverClass set (driverClass-3)]
    :baseCharge.
xrule bonusMalus/7:
      [carAccidents gt 1,
       driverClass in [1 to 2]]
    ==>
      [driverClass set -1]
    :baseCharge.
xrule bonusMalus/8:
      [carAccidents eq 2,
       driverClass eq 3]
    ==>
      [driverClass set 0]
    :baseCharge.
xrule bonusMalus/9:
      [carAccidents eq 2,
       driverClass in [4 to 5]]
    ==>
      [driverClass set 1]
    :baseCharge.
xrule bonusMalus/10:
      [carAccidents eq 2,
       driverClass eq 6]
    ==>
      [driverClass set 2]
    :baseCharge.
xrule bonusMalus/11:
      [carAccidents eq 2,
       driverClass in [7 to 8]]
    ==>
      [driverClass set 3]
    :baseCharge.
xrule bonusMalus/12:
      [carAccidents eq 2,
       driverClass eq 9]
    ==>
      [driverClass set 4]
    :baseCharge.
xrule bonusMalus/13:
      [carAccidents gt 2,
       driverClass in [-1 to 8]]
    ==>
      [driverClass set -1]
    :baseCharge.
xrule bonusMalus/14:
      [carAccidents gt 2,
       driverClass eq 9]
    ==>
      [driverClass set 0]
    :baseCharge.
xrule bonusMalus/15:
      [carAccidents eq any,
       driverClass eq any]
    ==>
      [driverClass set driverClass]
    :baseCharge.

xrule baseCharge/1:
      [carCapacity lt 900]
    ==>
      [baseValue set 537.00,
       resultValue set 537]
    :baseChargeModifiers.
xrule baseCharge/2:
      [carCapacity in [901 to 1300]]
    ==>
      [baseValue set 753.00,
       resultValue set 753]
    :baseChargeModifiers.
xrule baseCharge/3:
      [carCapacity in [1301 to 1600]]
    ==>
      [baseValue set 1050.00,
       resultValue set 1050]
    :baseChargeModifiers.
xrule baseCharge/4:
      [carCapacity in [1601 to 2000]]
    ==>
      [baseValue set 1338.00,
       resultValue set 1338]
    :baseChargeModifiers.
xrule baseCharge/5:
      [carCapacity gt 2000]
    ==>
      [baseValue set 1536.00,
       resultValue set 1536]
    :baseChargeModifiers.
xrule baseCharge/6:
      [carCapacity eq any]
    ==>
      [baseValue set baseValue,
       resultValue set resultValue]
    :baseChargeModifiers.

xrule baseChargeModifiers/1:
      [driverClass eq -1,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set 160].
xrule baseChargeModifiers/2:
      [driverClass eq 0,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set 60].
xrule baseChargeModifiers/3:
      [driverClass eq 1,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set 0].
xrule baseChargeModifiers/4:
      [driverClass eq 2,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -10.000].
xrule baseChargeModifiers/5:
      [driverClass eq 3,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -20.000].
xrule baseChargeModifiers/6:
      [driverClass eq 4,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -30.000].
xrule baseChargeModifiers/7:
      [driverClass eq 5,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -40.000].
xrule baseChargeModifiers/8:
      [driverClass eq 6,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -40.000].
xrule baseChargeModifiers/9:
      [driverClass eq 7,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -50.000].
xrule baseChargeModifiers/10:
      [driverClass eq 8,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -50.000].
xrule baseChargeModifiers/11:
      [driverClass eq 9,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set -60.000].
xrule baseChargeModifiers/12:
      [driverClass eq any,
       driverAge in [40 to 55],
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue-10)].
xrule baseChargeModifiers/13:
      [driverClass eq any,
       driverAge eq any,
       carAge lte 2,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set ((baseModifierValue+(5*carAge))-20.000)].
xrule baseChargeModifiers/14:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq single,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue-10)].
xrule baseChargeModifiers/15:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq 1,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue-10)].
xrule baseChargeModifiers/16:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars gt 1,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue-10)].
xrule baseChargeModifiers/17:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq 1,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue-20)].
xrule baseChargeModifiers/18:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq 1,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue-50.000)].
xrule baseChargeModifiers/19:
      [driverClass eq any,
       driverAge lt 25,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue+50.000)].
xrule baseChargeModifiers/20:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage lt 3,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue+30.000)].
xrule baseChargeModifiers/21:
      [driverClass eq any,
       driverAge eq any,
       carAge gt 10,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue+15.000)].
xrule baseChargeModifiers/22:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats in [6 to 9],
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue+20.000)].
xrule baseChargeModifiers/23:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq 0,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue+20.000)].
xrule baseChargeModifiers/24:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq instalments,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set (baseModifierValue+10)].
xrule baseChargeModifiers/25:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq 0]
    ==>
      [baseModifierValue set (baseModifierValue+60.000)].
xrule baseChargeModifiers/26:
      [driverClass eq any,
       driverAge eq any,
       carAge eq any,
       insurancePayment eq any,
       insuranceContinue eq any,
       insuranceCars eq any,
       insuranceOtherins eq any,
       carHistoric eq any,
       driverLicage eq any,
       carSeats eq any,
       carTechnical eq any,
       insuranceCertificate eq any]
    ==>
      [baseModifierValue set baseModifierValue]
    :main/1.


%%%%%%%%%%%%%%%%%%%%%%%%% STATES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%

xstat input/1: [insuranceCars,1].
xstat input/1: [driverClass,1].
xstat input/1: [insuranceContinue,1].
xstat input/1: [driverLicage,2].
xstat input/1: [carAccidents,0].
xstat input/1: [carTechnical,1].
xstat input/1: [carSeats,5].
xstat input/1: [driverAge,29].
xstat input/1: [carHistoric,0].
xstat input/1: [insuranceCertificate,1].
xstat input/1: [insurancePayment,single].
xstat input/1: [carAge,12].
xstat input/1: [carCapacity,997].
xstat input/1: [insuranceOtherins,0].
xstat input/2: [insuranceCars,1].
xstat input/2: [driverClass,1].
xstat input/2: [insuranceContinue,0].
xstat input/2: [driverLicage,2].
xstat input/2: [carAccidents,0].
xstat input/2: [carTechnical,0].
xstat input/2: [carSeats,5].
xstat input/2: [driverAge,23].
xstat input/2: [carHistoric,1].
xstat input/2: [insuranceCertificate,0].
xstat input/2: [insurancePayment,single].
xstat input/2: [carAge,14].
xstat input/2: [carCapacity,1900].
xstat input/2: [insuranceOtherins,0].
xstat input/3: [insuranceCars,2].
xstat input/3: [driverClass,7].
xstat input/3: [insuranceContinue,1].
xstat input/3: [driverLicage,10].
xstat input/3: [carAccidents,0].
xstat input/3: [carTechnical,0].
xstat input/3: [carSeats,5].
xstat input/3: [driverAge,50].
xstat input/3: [carHistoric,1].
xstat input/3: [insuranceCertificate,0].
xstat input/3: [insurancePayment,single].
xstat input/3: [carAge,1].
xstat input/3: [carCapacity,1900].
xstat input/3: [insuranceOtherins,1].

%%%%%%%%%%%%%%%%%%%%%%%%% CALLBACKS DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% File generated by HeKatE Qt Editor ver. M6_10_1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

