%
% $Id: vasProlog.cpp,v 1.7.8.4 2011-09-29 09:18:04 kkr Exp $
%
% File generated by HeKatE Qt Editor ver. M6_10_1
%
% HeaRT case
%
%
%     Copyright (C) 2006-9 by the HeKatE Project
%
%     HeaRT has been develped by the HeKatE Project, 
%     see http://hekate.ia.agh.edu.pl
%
%     This file is part of HeaRT.
%
%     HeaRT is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     HeaRT is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with HeaRT.  If not, see <http://www.gnu.org/licenses/>.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

:- ensure_loaded('heart.pl').

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TYPES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%

xtype [name: boolean,
       base: numeric,
       length: 1,
       scale: 0,
       desc: boolean,
       domain: [0,1]
      ].
xtype [name: integer,
       base: numeric,
       length: 10,
       scale: 0,
       desc: integer,
       domain: [-2147483647 to 2147483647]
      ].


xtype [name: ard_default_type,
       base: symbolic,
       domain: [none/1],
       ordered: yes
      ].
xtype [name: activity_type,
       base: symbolic,
       desc: 'User activity',
       domain: [walking,driving,running,still]
      ].
xtype [name: interests_type,
       base: symbolic,
       desc: 'Different user interests',
       domain: [sport,shopping,culture,sightseeing,eating,entertainment]
      ].
xtype [name: weather_type,
       base: symbolic,
       desc: 'Wheater type',
       domain: [sunny,rainy,cloudy]
      ].
xtype [name: poi_type,
       base: symbolic,
       desc: 'Different points of interests',
       domain: [indoor-eating,outdor-eating,drivethrough-eating,indoor-sports,outdoor-sports,theatre-cinema,monuments,indoor-concert,outdoor-concert,museum,shopping-center]
      ].
xtype [name: hour_type,
       base: numeric,
       domain: [0.000 to 23.000]
      ].

%%%%%%%%%%%%%%%%%%%%%%%%% ATTRIBUTES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%

xattr [name: activity,
       abbrev: acti1,
       class: simple,
       type: activity_type,
       comm: inter
      ].
xattr [name: hour,
       abbrev: hour1,
       class: simple,
       type: hour_type,
       comm: inter
      ].
xattr [name: poi,
       abbrev: poi1,
       class: simple,
       type: poi_type,
       comm: inter
      ].
xattr [name: weather,
       abbrev: weat1,
       class: simple,
       type: weather_type,
       comm: inter
      ].
xattr [name: '{user_profile}',
       abbrev: '{use1}',
       class: general,
       type: interests_type,
       comm: inter
      ].

%%%%%%%%%%%%%%%%%%%%%%%% TABLE SCHEMAS DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%

xschm 'Recommendations': [weather,'{user_profile}',activity] ==> [poi].

%%%%%%%%%%%%%%%%%%%%%%%%%%%% RULES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%

xrule 'Recommendations'/1:
      [weather in [sunny,cloudy],
       '{user_profile}' sim [eating],
       activity eq any]
    ==>
      [poi set outdor-eating].
xrule 'Recommendations'/2:
      [weather in [rainy],
       '{user_profile}' sim [eating],
       activity in [walking,running]]
    ==>
      [poi set indoor-eating].
xrule 'Recommendations'/3:
      [weather in [rainy],
       '{user_profile}' sim [eating],
       activity in [driving]]
    ==>
      [poi set drivethrough-eating].
xrule 'Recommendations'/4:
      [weather in [rainy,cloudy],
       '{user_profile}' sim [culture,entertainment],
       activity in [walking,driving]]
    ==>
      [poi set theatre-cinema].
xrule 'Recommendations'/5:
      [weather in [rainy,cloudy],
       '{user_profile}' sim [culture,sightseeing],
       activity in [walking,driving]]
    ==>
      [poi set museum].
xrule 'Recommendations'/6:
      [weather in [sunny],
       '{user_profile}' sim [sightseeing,culture],
       activity eq any]
    ==>
      [poi set monuments].


%%%%%%%%%%%%%%%%%%%%%%%%% STATES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%% CALLBACKS DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% File generated by HeKatE Qt Editor ver. M6_10_1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
