%
% $Id: vasProlog.cpp,v 1.7.8.4 2011-09-29 09:18:04 kkr Exp $
%
% File generated by HeKatE Qt Editor ver. M6_10_1
%
% HeaRT case
%
%
%     Copyright (C) 2006-9 by the HeKatE Project
%
%     HeaRT has been develped by the HeKatE Project, 
%     see http://hekate.ia.agh.edu.pl
%
%     This file is part of HeaRT.
%
%     HeaRT is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     HeaRT is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with HeaRT.  If not, see <http://www.gnu.org/licenses/>.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

:- ensure_loaded('heart.pl').

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% TYPES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%

xtype [name: boolean,
       base: numeric,
       length: 1,
       desc: boolean,
       domain: [0,1]
      ].
xtype [name: integer,
       base: numeric,
       length: 10,
       desc: integer,
       domain: [-2147483647 to 2147483647]
      ].


xtype [name: ard_default_type,
       base: symbolic,
       domain: [none/1],
       ordered: yes
      ].
xtype [name: location_type,
       base: symbolic,
       domain: [home,work,outside]
      ].
xtype [name: time_type,
       base: symbolic,
       domain: [morning,noon,afternoon,evening,night]
      ].
xtype [name: hour_type,
       base: numeric,
       domain: [0.000 to 23.000]
      ].
xtype [name: today_type,
       base: symbolic,
       domain: [weekend,workday]
      ].
xtype [name: action_type,
       base: symbolic,
       domain: [leaving,working,sleeping,travelling]
      ].
xtype [name: day_type,
       base: symbolic,
       domain: [mon/1,tue/2,wed/3,thu/4,fri/5,sat/6,sun/7],
       ordered: yes
      ].
xtype [name: threat_type,
       base: symbolic,
       domain: [road_threat,pedestrian_threat,building_threat]
      ].
xtype [name: activity_type,
       base: symbolic,
       domain: [walking,driving,cycling,idle,running]
      ].

%%%%%%%%%%%%%%%%%%%%%%%%% ATTRIBUTES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%

xattr [name: action,
       abbrev: acti1,
       class: simple,
       type: action_type,
       comm: inter
      ].
xattr [name: activity,
       abbrev: acti2,
       class: simple,
       type: activity_type,
       comm: in
      ].
xattr [name: day,
       abbrev: day1,
       class: simple,
       type: day_type,
       comm: inter
      ].
xattr [name: daytime,
       abbrev: dayt1,
       class: simple,
       type: time_type,
       comm: inter
      ].
xattr [name: hour,
       abbrev: hour1,
       class: simple,
       type: hour_type,
       comm: inter
      ].
xattr [name: location,
       abbrev: loca1,
       class: simple,
       type: location_type,
       comm: in
      ].
xattr [name: today,
       abbrev: toda1,
       class: simple,
       type: today_type,
       comm: inter
      ].
xattr [name: '{threat}',
       abbrev: '{thr1}',
       class: general,
       type: threat_type,
       comm: out
      ].

%%%%%%%%%%%%%%%%%%%%%%%% TABLE SCHEMAS DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%

xschm 'DayTime': [hour] ==> [daytime].
xschm 'Today': [day] ==> [today].
xschm 'Actions': [location,daytime,today] ==> [action].
xschm 'Threats': [action,activity] ==> ['{threat}'].

%%%%%%%%%%%%%%%%%%%%%%%%%%%% RULES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%

xrule 'DayTime'/1:
      [hour in [14.000 to 18.000]]
    ==>
      [daytime set afternoon].
xrule 'DayTime'/2:
      [hour in [6.000 to 11.000]]
    ==>
      [daytime set morning]
    :'Actions'.
xrule 'DayTime'/3:
      [hour in [19.000 to 23.000,0.000 to 5.000]]
    ==>
      [daytime set night].
xrule 'DayTime'/4:
      [hour in [12.000 to 13.000]]
    ==>
      [daytime set noon].

xrule 'Today'/1:
      [day in [mon to fri]]
    ==>
      [today set workday]
    :'Actions'.
xrule 'Today'/2:
      [day in [sat to sun]]
    ==>
      [today set weekend].

xrule 'Actions'/1:
      [location eq home,
       daytime eq morning,
       today eq workday]
    ==>
      [action set leaving]
    :'Threats'.
xrule 'Actions'/2:
      [location eq home,
       daytime eq night,
       today eq any]
    ==>
      [action set sleeping].
xrule 'Actions'/3:
      [location eq work,
       daytime eq afternoon,
       today eq workday]
    ==>
      [action set leaving].
xrule 'Actions'/4:
      [location eq outside,
       daytime eq any,
       today eq any]
    ==>
      [action set travelling].

xrule 'Threats'/1:
      [action in [leaving,travelling],
       activity in [walking,running]]
    ==>
      ['{threat}' set [pedestrian_threat]].
xrule 'Threats'/2:
      [action in [leaving,travelling],
       activity in [driving,cycling]]
    ==>
      ['{threat}' set [road_threat]].
xrule 'Threats'/3:
      [action in [sleeping,working],
       activity in [idle]]
    ==>
      ['{threat}' set [building_threat]].

%%%%%%%%%%%%%%%%%%%%%%%%% STATES DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%% CALLBACKS DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% File generated by HeKatE Qt Editor ver. M6_10_1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%